backend:
  name: github
  branch: staging
  open_authoring: true
  repo: asafamr/spacify
publish_mode: editorial_workflow
media_library:
  name: disabled
collections: # replaced by script
  - name: "template" 
    label: "Blog" 
    format: "json-frontmatter"
    extension: "json"
    folder: "space_data" 
    path: "{{category}}/{{uid}}"
    create: true 
    fields: 
      - {label: "$schema", name: "$schema", widget: "hidden",default: "../something.json"}
      - {label: "Body", name: "body", widget: "markdown"}